// <auto-generated> </auto-generated>
#nullable enable
namespace Test.Services
{
    using Data.Context;
    public abstract class TestsBase : IDisposable
    {
        protected readonly SQLiteContext ContextProxy;

        protected TestsBase(string db)
        {
            ContextProxy = new SQLiteContext(db);
        }

        public void Dispose()
        {
            ContextProxy.DropDatabase();
        }
    }
}
