// <auto-generated> </auto-generated>
#nullable enable


namespace Data.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    /// <summary>
    /// Represents product characteristics.
    /// </summary>
    public class Characteristic
    {
        /// <summary>
        /// Initializes a new instance/> class.
        /// </summary>
        public Characteristic() { }

        /// <summary>
        /// Initializes a new instance of the <see /> class with specified parameters.
        /// </summary>
        public Characteristic
        (
            string productType,
            string category,
            string description,
            string manufacturer,
            string country,
            DateOnly manufactureDate,
            ProductStatus status
        )
        {
            ProductType = productType;
            Category = category;
            Description = description;
            Manufacturer = manufacturer;
            Country = country;
            ManufactureDate = manufactureDate;
            Status = status;
        }

        /// <summary>
        /// Product characteristic.
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Product type.
        /// </summary>
        [Required]
        public string? ProductType { get; set; }

        /// <summary>
        /// Category of the product.
        /// </summary>
        [Required]
        public string? Category { get; set; }

        /// <summary>
        /// Gets or sets the description of the product.
        /// </summary>
        [Required]
        public string? Description { get; set; }

        /// <summary>
        /// Manufacturer of the product.
        /// </summary>
        [Required]
        public string? Manufacturer { get; set; }

        /// <summary>
        /// Country of origin of the product.
        /// </summary>
        [Required]
        public string? Country { get; set; }

        /// <summary>
        /// date.
        /// </summary>
        public DateOnly ManufactureDate { get; set; }

        /// <summary>
        /// Status of the product.
        /// </summary>
        public ProductStatus Status { get; set; }

        /// <summary>
        /// Gets or sets the product associated with this characteristic.
        /// </summary>
        [Required]
        [ForeignKey("ProductId")]
        public Product? Product { get; set; }
    }

    /// <summary>
    /// Enumeration representing the status of a product.
    /// </summary>
    public enum ProductStatus
    {
        New, Used, OpenBox, Refurbished
    }
}
