// <auto-generated> </auto-generated>
#nullable enable
namespace Data.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    /// <summary>
    /// Represents a user's product.
    /// </summary>
    /// <remarks>
    /// In the database, this class is used to store information about products
    /// associated with users or clients. Each product has a unique identifier (ID),
    /// a name, a price, and a reference to its characteristics.
    /// </remarks>
    public class Product
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Product"/> class.
        /// </summary>
        public Product()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="Product"/> class with specified parameters.
        /// </summary>
        /// <param name="name">The name of the product.</param>
        /// <param name="price">The price of the product.</param>
        /// <param name="characteristic">The characteristics of the product.</param>
        public Product(string name, int price, Characteristic characteristic)
        {
            Name = name;
            Price = price;
            Characteristic = characteristic;
        }

        /// <summary>
        /// Gets or sets the unique identifier of the product.
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the name of the product.
        /// </summary>
        [Required]
        [MinLength(2)]
        [MaxLength(300)]
        public string? Name { get; set; }

        /// <summary>
        /// Gets or sets the price of the product.
        /// </summary>
        public int Price { get; set; }

        /// <summary>
        /// Gets or sets the characteristics of the product.
        /// </summary>
        [Required]
        public Characteristic? Characteristic { get; set; }

        /// <summary>
        /// Gets or sets the user associated with the product.
        /// </summary>
        [Required]
        [ForeignKey("UserId")]
        public User? User { get; set; }

        /// <summary>
        /// Gets or sets the client associated with the product.
        /// </summary>
        [ForeignKey("ClientId")]
        public Client? Client { get; set; }
    }
}
