// <auto-generated> </auto-generated>
#nullable enable


namespace Data.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    /// <summary>
    /// Represents a reminder associated with a user and optionally a client.
    /// </summary>
    /// <remarks>
    /// In the database, this class is used to store information about reminders,
    /// including the note, description, scheduled time, associated user, and optionally associated client.
    /// </remarks>
    public class Reminder
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Reminder"/> class.
        /// </summary>
        public Reminder() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="Reminder"/> class with specified parameters.
        /// </summary>
        /// <param name="note">The note or title of the reminder.</param>
        /// <param name="description">The description of the reminder.</param>
        /// <param name="when">The scheduled time of the reminder.</param>
        /// <param name="user">The user associated with the reminder.</param>
        /// <param name="client">The client associated with the reminder (optional).</param>
        public Reminder(string note, string description, DateTime when, User user, Client? client)
        {
            Note = note;
            Description = description;
            When = when;
            Client = client;
            User = user;
        }

        /// <summary>
        /// Gets or sets the unique identifier of the reminder.
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the note or title of the reminder.
        /// </summary>
        [Required]
        [MaxLength(300)]
        public string? Note { get; set; }

        /// <summary>
        /// Gets or sets the description of the reminder.
        /// </summary>
        [MaxLength(3000)]
        public string? Description { get; set; }

        /// <summary>
        /// Gets or sets the scheduled time of the reminder.
        /// </summary>
        public DateTime When { get; set; }

        /// <summary>
        /// Gets or sets the client associated with the reminder (optional).
        /// </summary>
        [ForeignKey("ClientId")]
        public Client? Client { get; set; }

        /// <summary>
        /// Gets or sets the user associated with the reminder.
        /// </summary>
        [Required]
        [ForeignKey("UserId")]
        public User? User { get; set; }
    }
}