// <auto-generated> </auto-generated>

namespace Business.Validators
{
    using System.Text.RegularExpressions;
    using Business.Validators.Exceptions;


    public static class PhoneNumberValidator
    {
        private const string PhoneNumberRegex = @"^\+(?:[0-9] ?){6,14}[0-9]$";

        public static void Validate(string phoneNumber)
        {
            if (!Regex.IsMatch(phoneNumber, PhoneNumberRegex))
            {
                throw new InvalidPhoneNumberException("Phone number must be a valid international phone number.");
            }
        }
    }
}


