// <auto-generated> </auto-generated>
namespace Data
{
    /// <summary>
    /// The main method for entering the project
    /// </summary>
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine();
        }
    }
}
